version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: post-md-app
    container_name: post_md_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    networks:
      - post_md_network

  web:
    image: nginx:alpine
    container_name: post_md_web
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - post_md_network

  db:
    image: postgres:15-alpine
    container_name: post_md_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: post_md_db
      POSTGRES_USER: post_md_user
      POSTGRES_PASSWORD: secret_password
    ports:
      - "5432:5432"
    volumes:
      - pgsql_data:/var/lib/postgresql/data
    networks:
      - post_md_network

networks:
  post_md_network:
    driver: bridge

volumes:
  pgsql_data: